### ISSUE TITLE
OK button does not work in TimeSheet editor (no error message)

### ISSUE THREAD

**Issue by nsfewer** [kimai/kimai#1013]
#### Expected behaviour
Upon editing a timesheet event pressing OK button should save changes.
#### Actual behaviour
Upon editing a timesheet event pressing OK button generates no response. Only CANCEL does.
#### Steps to reproduce
1. Create a new timesheet event
2. Save immediately or after some changes
3. Press OK button
#### Reproducable on demo.kimai.org? [yes|no]
no
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
v1.1.0.1389
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
DEBUG network in browser: 
jquery-1.9.1.min.js:4 POST http://tidsreg.studie49.dk/extensions/ki_timesheets/processor.php 500 (Internal Server Error)
Logfile.txt:
02.08.2017 15:08:25] login: admin as user
[02.08.2017 15:08:41] KSPI axAction (admin): refreshSubtab
[02.08.2017 15:08:41] KSPI axAction (admin): refreshSubtab
[02.08.2017 15:08:41] KSPI axAction (admin): refreshSubtab
[02.08.2017 15:08:45] KSPI axAction (admin): add_edit_customer
[02.08.2017 15:08:55] KSPI axAction (admin): add_edit_CustomerProjectActivity
[02.08.2017 15:08:55] KSPI axAction (admin): reload_customers
[02.08.2017 15:08:55] KSPI axAction (admin): refreshSubtab
[02.08.2017 15:08:55] KSPI axAction (admin): reload_projects
[02.08.2017 15:08:55] KSPI axAction (admin): refreshSubtab
[02.08.2017 15:08:57] KSPI axAction (admin): add_edit_customer
[02.08.2017 15:09:04] KSPI axAction (admin): reload_timeSheet
[02.08.2017 15:09:08] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 15:09:08] KSPI axAction (admin): reload_activities_options
[02.08.2017 15:09:24] KSPI axAction (admin): allFittingFixedRates
[02.08.2017 15:09:29] KSPI axAction (admin): allFittingRates
[02.08.2017 15:09:31] KSPI axAction (admin): allFittingRates
[02.08.2017 15:09:38] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 15:09:42] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 15:12:01] KSPI axAction (admin): add_edit_timeSheetEntry

../core/error.log:
[01-Aug-2017 22:17:45 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[01-Aug-2017 22:17:45 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[01-Aug-2017 22:17:45 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 28
[01-Aug-2017 22:17:58 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[01-Aug-2017 22:17:58 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[01-Aug-2017 22:17:58 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 28
[02-Aug-2017 00:18:19 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 00:18:19 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 00:18:19 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 00:29:33 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 00:29:33 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 00:29:33 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 00:33:10 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 00:33:10 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 00:33:10 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 00:55:15 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 00:55:15 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 00:55:15 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 13:18:15 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 13:18:15 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 13:18:15 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 13:50:01 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 13:50:01 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 13:50:01 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 14:33:14 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:33:14 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:33:14 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 14:33:19 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:33:19 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:33:19 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 14:37:47 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:37:47 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:37:47 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 14:38:34 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:38:34 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:38:34 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 14:49:17 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:49:17 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:49:17 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 14:49:28 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:49:28 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:49:28 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 14:59:58 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:59:58 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 14:59:58 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 15:03:36 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 15:03:36 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 15:03:36 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 15:04:28 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 15:04:28 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 15:04:28 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30
[02-Aug-2017 15:08:15 Europe/Copenhagen] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 15:08:15 Europe/Copenhagen] PHP Warning:  file_get_contents(https://raw.githubusercontent.com/kimai/kimai/master/kimai.json): failed to open stream: no suitable wrapper could be found in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 32
[02-Aug-2017 15:08:15 Europe/Copenhagen] PHP Catchable fatal error:  Argument 1 passed to Kimai_Update_Version::__construct() must be of the type array, null given, called in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Check.php on line 35 and defined in /home/n294129/public_html/tidsreg/libraries/Kimai/Update/Version.php on line 30

../extensions/ki_timesheets/error.log:

[02-Aug-2017 15:04:48 Europe/Copenhagen] PHP Fatal error:  Call to undefined function iconv_strpos() in /home/n294129/public_html/tidsreg/libraries/zendframework/zendframework1/library/Zend/Locale/Format.php on line 827
[02-Aug-2017 15:09:38 Europe/Copenhagen] PHP Fatal error:  Call to undefined function iconv_strpos() in /home/n294129/public_html/tidsreg/libraries/zendframework/zendframework1/library/Zend/Locale/Format.php on line 827
[02-Aug-2017 15:09:42 Europe/Copenhagen] PHP Fatal error:  Call to undefined function iconv_strpos() in /home/n294129/public_html/tidsreg/libraries/zendframework/zendframework1/library/Zend/Locale/Format.php on line 827
[02-Aug-2017 15:12:01 Europe/Copenhagen] PHP Fatal error:  Call to undefined function iconv_strpos() in /home/n294129/public_html/tidsreg/libraries/zendframework/zendframework1/library/Zend/Locale/Format.php on line 827
[02-Aug-2017 15:13:00 Europe/Copenhagen] PHP Fatal error:  Call to undefined function iconv_strpos() in /home/n294129/public_html/tidsreg/libraries/zendframework/zendframework1/library/Zend/Locale/Format.php on line 827

**Comment by simonschaufi** [comment]
> jquery-1.9.1.min.js:4 POST http:///extensions/ki_timesheets/processor.php 500 (Internal Server Error)

I think you are doing something terribly wrong. Where is the hostname?

**Comment by nsfewer** [comment]
Sorry I removed it on forgot to type a <host name> substitution:
jquery-1.9.1.min.js:4 POST http://tidsreg.studie49.dk/extensions/ki_timesheets/processor.php 500 (Internal Server Error)

**Comment by simonschaufi** [comment]
ah ok. well, I can't say anything about internal server error. please check your php error log.

**Comment by nsfewer** [comment]
This is logfile.txt:

[02.08.2017 16:24:49] login: admin as user
[02.08.2017 16:24:57] KSPI axAction (admin): setTimeframe
[02.08.2017 16:24:57] KSPI axAction (admin): startRecord
[02.08.2017 16:24:57] KSPI axAction (admin): reload_timeSheet
[02.08.2017 16:24:58] KSPI axAction (admin): stopRecord
[02.08.2017 16:24:58] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 16:24:58] KSPI axAction (admin): reload_timeSheet
[02.08.2017 16:24:58] KSPI axAction (admin): reload_activities_options
[02.08.2017 16:25:01] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 16:25:02] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 16:25:06] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 16:25:08] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 16:25:18] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 16:31:24] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 16:31:24] KSPI axAction (admin): reload_activities_options
[02.08.2017 16:31:25] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 16:31:26] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 16:31:27] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 16:31:28] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 16:31:29] KSPI axAction (admin): add_edit_timeSheetEntry

Here comes error.log from kimai main folder:
[02-Aug-2017 16:22:17 Europe/Copenhagen] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /home/n294129/public_html/tidsreg/libraries/phpclasses/ultimatemysql/mysql.class.php:1063
Stack trace:
#0 /home/n294129/public_html/tidsreg/libraries/phpclasses/ultimatemysql/mysql.class.php(80): MySQL->Open()
#1 /home/n294129/public_html/tidsreg/libraries/Kimai/Database/Mysql.php(76): MySQL->__construct(true, 'n294129_kimai', 'localhost', 'n294129_kadmin', 'EcunNDlP0xXlPux...')
#2 /home/n294129/public_html/tidsreg/libraries/Kimai/Database/Mysql.php(57): Kimai_Database_Mysql->connect('localhost', 'n294129_kimai', 'n294129_kadmin', 'EcunNDlP0xXlPux...', 0)
#3 /home/n294129/public_html/tidsreg/includes/basics.php(51): Kimai_Database_Mysql->__construct(Array, true)
#4 /home/n294129/public_html/tidsreg/index.php(46): require_once('/home/n294129/p...')
#5 {main}
  thrown in /home/n294129/public_html/tidsreg/libraries/phpclasses/ultimatemysql/mysql.class.php on line 1063

I can't find the general php log file on the webhotel.

**Comment by nsfewer** [comment]
After changing to PHP7.0 I got rid of the 500 error and it returnes 200 OK.
But.. the button still doen't save the event data.

I get this error: 200 POST processor.php tidsreg.studie49.dk

     SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

Form data from Mozilla Firefox Debug:
id	"220"
axAction	"add_edit_timeSheetEntry"
projectID	"36"
filter	""
activityID	"71"
description	""
start_day	"02.08.2017"
end_day	"02.08.2017"
start_time	"21:26:00"
end_time	"21:26:00"
duration	"00:00:00"
location	"Rweqweqw"
trackingNumber	""
comment	""
commentType	"0"
userID	"823938144"
budget	""
approved	""
statusID	"1"
billable	"0"
rate	"300.00"
fixedRate	"600.00"

**Comment by nsfewer** [comment]
../temporay/logfile shows now:

[02.08.2017 21:43:09] KSPI axAction (admin): add_edit_timeSheetEntry
[02.08.2017 21:43:09] Uncaught exception: Call to undefined function iconv_strpos()

**Comment by simonschaufi** [comment]
please read http://www.kimai.org/documentation/installation/index.html
