### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by eglyn** [kimai/kimai#182]
Hi :)
i am trying to install kimai v2, but i have a problem with the command composer install --no-dev:

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "WebServerBundle" from namespace "Symfony\Bundle\WebServerBundle".
!!  Did you forget a "use" statement for another namespace? in /var/www/html/kimai2/src/Kernel.php:48
!!  Stack trace:
!!  #0 /var/www/html/kimai2/vendor/symfony/http-kernel/Kernel.php(409): App\Kernel->registerBundles()
!!  #1 /var/www/html/kimai2/vendor/symfony/http-kernel/Kernel.php(120): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /var/www/html/kimai2/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /var/www/html/kimai2/vendor/symfony/console/Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #4 /var/www/html/kimai2/bin/console(39): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
!!  #5 {main}
!!    thrown in /var/www/html/kimai2/src/Kernel.php on line 48
!!
Script @auto-scripts was called via post-install-cmd
```

i m not familiar with composer, i m doing probably something wrong :/

my server: 
centos 7
php 7.3
mariadb
httpd webserver

any idea ?

thx :)

**Comment by kevinpapst** [comment]
Seems you have development environment `activated` , check your `.env` file - see https://github.com/kevinpapst/kimai2/blob/master/.env.dist#L9

And you are trying to install for production: `composer install --no-dev`. 
So you have conflicting settings. 
Just install by executing `composer install`.

I'll check/update the documentation to make it clearer.

**Comment by eglyn** [comment]
yes ! that's it, it's working now :)
thx :)
